### PR TITLE
Add harmonia cache-server

### LINKED ISSUE #12: Add cache server
Following #7 expose the NixOS machine's Nix store as cache server so we can ditch cachix (automatically resolving https://github.com/nammayatri/nammayatri/issues/9411 in the process).

### PR DESCRIPTION
**Pull request by srid**
resolves #12

### CODE REVIEW

**Comment by shivaraj-bh** [comment]
I noticed that `cache.nixos.org` was being prioritised over the self-hosted cache. It is because of `cache.nixos.org` having a priority of `40`, over [harmonia’s 50](https://github.com/nix-community/harmonia/blob/e7cd871ae67fd0ed3ec1db6acc336e499110fe70/module.nix#L59-L64). 

We can either configure at the server-side to have lower priority or at the client side by adding the query param `?priority=<something-lower-than-40>` in [flake.nix’s `nixConfig`](https://github.com/nammayatri/nammayatri/blob/34aff49fc14f1031eb3418e9068ab84591cf0973/flake.nix#L6)

**Comment by srid** [comment]
I think we should override priority so our cache is favoured (it would be local, thus faster). Without our cache, it can take ~6 hours to build nammayatri.

I'll set the priority on the server side. We can do the same for Juspay internal cache server as well ...

**Comment by shivaraj-bh** [comment]
I might be wrong, but because we are using Tailscale funnel in NY, won't the traffic be routed via Tailscale servers?

**Comment by srid** [comment]
Hmm, I assumed that their DNS would resolve [to the closest server](https://tailscale.com/kb/1232/derp-servers) but that appears to not be the case (checking with `nix run nixpkgs#dig ny-ci-nixos.betta-gray.ts.net`) because - no matter where I resolve it form (Bangalore; Quebec), it resolves to an Australian IP, which has worse ping than cache.nixos.org (on fastly).

I'll revert the priority change. 

But since our CI machine is literally in the same building, it would make sense to avoid the global roundtrip (even to cache.nixos.org). One way to solve this is to run nginx reverse proxy on DigitialOcean (Bangalore region), connecting to the harmonia server via tailscale network (which would be direct), but we should still formally measure the transfer speeds between this setup and cache.nixos.org.

(For Juspay internal cache as it is now, this won't matter as the name resolves to a local IP already)

**Comment by srid** [comment]
> One way to solve this is to run nginx reverse proxy on DigitialOcean (Bangalore region), connecting to the harmonia server via tailscale network (which would be direct), but we should still formally measure the transfer speeds between this setup and cache.nixos.org.

However, this still wouldn't solve the situation of people *in office* using the cache, since ideally we want them to download through a direct connection to the machine in the same office (not through a DigitalOcean hop).

**Pull request merged**
